FROM ghcr.io/prefix-dev/pixi:0.37.0 AS build

RUN apt-get update && apt-get install -y build-essential

WORKDIR /app
COPY pyproject.toml ui.py ./

RUN pixi install
RUN echo '#!/bin/bash
exec "$@" 2>&1' > /shell-hook.sh && chmod +x /shell-hook.sh

FROM ghcr.io/prefix-dev/pixi:0.37.0 AS runtime

COPY --from=build /app /app
COPY --from=build /shell-hook.sh /shell-hook.sh
WORKDIR /app

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["/bin/bash", "/shell-hook.sh"]
CMD ["pixi", "run", "python", "ui.py"]
